### ISSUE TITLE
Time keeps fluctuating

### ISSUE THREAD

**Issue by quaintdev** [daledavies/jump#16] opened 2022-03-18 03:29 UTC
I saw a weird behavior with my setup. The time on startpage keeps changing by 12 hours and sometimes NaN. This changes greetings from Good Morning to Good Night and then Good undefined. I am using arm image by @Just5KY. Both time on my system and server are properly set. Also I see half hour delay with the time when it is close to my actual time.

![image](https://user-images.githubusercontent.com/59229571/158931956-f7ae1a27-77a9-40eb-9402-7266805c21df.png)

**Comment by Just5KY** [comment] 2022-03-18 03:37
That's weird.
Did to put in the environment variable for location.

I didn't do it in my testing
Its 9 am right now my time it says 3 am.
I will try setting the env. later to test this

![Uploading t2{8dee363} (473bb17b-e9fe-4298-ae57-d562f2ebcbf0 id=0x7f0a03ac tag=BaseCommentFragment) …]()

**Comment by quaintdev** [comment] 2022-03-18 03:41
Yes I have set `SITENAME`, `OWMAPIKEY`, `LATLONG` environment variables.

**Comment by Just5KY** [comment] 2022-03-18 03:43
Ok 
I will add `OWMAPIKEY`, `LATLONG` in my compose and test it

**Comment by Just5KY** [comment] 2022-03-18 04:03
### Yup, happening to me too.

![image](https://user-images.githubusercontent.com/71321862/158935210-7393cf3b-556d-498c-9e53-00d3db9c78c4.png)

```yml
  jump:
    image: justsky/jump
    container_name: jump
    restart: unless-stopped
    ports:
      - 8321:8080
    volumes:
      - $DOCKERDIR/jump/backgrounds:/backgrounds
      - $DOCKERDIR/jump/sites:/sites
    environment:
      SITENAME: 'SkyPi'
      OWMAPIKEY: 
      LATLONG: 
      CACHEBYPASS: 'true'
      TZ: $TZ 
```
### I even tried adding Timezone env

**Comment by Just5KY** [comment] 2022-03-18 04:12
I saw that there is another branch based on similar issue, 
I will build from that branch to test it

https://github.com/daledavies/jump/commit/1b1c7d814e98533292ebc8ad5c45c906177790c6

**Comment by quaintdev** [comment] 2022-03-18 04:23
The fix on that branch was for an issue where it was showing time different from local time zone. The time was in constant lag or lead with current time. It was not fluctuating like in this case. I don't think that fix will resolve this issue. @daledavies  can confirm.

**Comment by Just5KY** [comment] 2022-03-18 05:05
### It starts with 1:30 hrs time difference
![image](https://user-images.githubusercontent.com/71321862/158940641-ed561584-3e96-4e77-927b-798a4fb31f3b.png)

### Then it shows the same time in 24hrs
![image](https://user-images.githubusercontent.com/71321862/158940649-5935403f-81f7-420b-ae8b-f2e4fcfb0f81.png)

### Then it goes NaN
![image](https://user-images.githubusercontent.com/71321862/158940667-9f7e49d5-bae0-4a39-87c6-2028cf09f494.png)

**Comment by itsinART** [comment] 2022-03-18 11:21
i'm facing the same issue.
running it on an synology docker environment with mentioned variables.

setting the wrong time on startup, later, after refreshing, its showing "**NaN:NaN**" instead of the acutal time and is welcoming me with "Good **Undefined**" instead of "Good Evening", i guess.. ;)

**Comment by daledavies** [comment] 2022-03-18 13:19
I've been able to recreate this locally, seems to happen if your browser returns a different timezone to the timezone of the latlong provided for the openweather api.

I'll keep plugging away to fix it :)

**Comment by daledavies** [comment] 2022-03-18 13:29
I think I know what the cause is. If Ipush a patch to a new branch is anyone in this thread able to build a local container image and test?

**Comment by daledavies** [comment] 2022-03-18 13:39
@quaintdev @Just5KY @itsinART There is a patch in the following branch, are you able to test it for me?

https://github.com/daledavies/jump/tree/issue-16-time

Thank you for your help with this :)

**Comment by quaintdev** [comment] 2022-03-18 14:24
It seems to be fixed. No fluctuations or NaN for past 5 minutes.

**Comment by daledavies** [comment] 2022-03-18 14:28
@quaintdev Excellent, thank you for getting back so quickly :) 

@itsinART No worries, thanks all the same though. I'll take the confirmation from quaintdev.

**Comment by Just5KY** [comment] 2022-03-19 01:02
Since you have added this issue-fix to main branch, I have pushed arm image to docker hub

https://hub.docker.com/r/justsky/jump/tags

**Comment by daledavies** [comment] 2022-03-19 22:14
Release v1.1.2 has been pushed, images updated on docker hub so closing this issue. Thank you again for everyone's input on this.

**Closed by daledavies** 2022-03-19 22:14 UTC
Labels: bug
