### ISSUE TITLE
Icons not loading

### ISSUE THREAD

**Issue by theonekili** [daledavies/jump#57] opened 2022-08-08 14:34 UTC
This is unfortunately inconsistent, but at times images aren't loaded correctly, resulting in a broken image.
![image](https://user-images.githubusercontent.com/61316292/183442224-44f397b0-2824-49ef-912c-cc4d5030bccd.png)

The value corresponding to "image"-key matches the name of the image stored in the icons directory.

I've checked the source and when following the link to the icon HTTP error 500 is returned.

**Comment by daledavies** [comment] 2022-08-12 13:40
Could you forward a snapshot of the docker logs after you have got the 500 error?

You can do this with `docker logs <CONTAINER NAME OR ID>` so in my case this is `docker logs jump_web_1`.

**Comment by theonekili** [comment] 2022-08-15 06:49
Hey Dale,

here's an excerpt of the logs, right after I provoked the 500 error :)

`NOTICE: PHP message: PHP Fatal error:  Uncaught Jump\Exceptions\SiteNotFoundException: The site could not be found (mailto:user@domain.com?subject=Subject) in /var/www/html/classes/Sites.php:141
Stack trace:
#0 /var/www/html/classes/API/Icon.php(28): Jump\Sites->get_site_by_url()
#1 /var/www/html/classes/Main.php(69): Jump\API\Icon->get_output()
#2 /var/www/html/index.php(22): Jump\Main->init()
#3 {main}
  thrown in /var/www/html/classes/Sites.php on line 141
2022/08/15 06:43:17 [error] 25#25: *15600 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Jump\Exceptions\SiteNotFoundException: The site could not be found (mailto:user@domain.com?subject=Subject) in /var/www/html/classes/Sites.php:141
Stack trace:
#0 /var/www/html/classes/API/Icon.php(28): Jump\Sites->get_site_by_url()
#1 /var/www/html/classes/Main.php(69): Jump\API\Icon->get_output()
#2 /var/www/html/index.php(22): Jump\Main->init()
#3 {main}
  thrown in /var/www/html/classes/Sites.php on line 141" while reading response header from upstream, client: 10.127.128.131, server: _, request: "GET /api/icon?siteurl=mailto%3Auser%40domain.com%3Fsubject%3DSubject HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "jump.domain.com:8123"
10.127.128.131 - - [15/Aug/2022:06:43:17 +0000] "GET /api/icon?siteurl=mailto%3Auser%40domain.com%3Fsubject%3DSubject HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36" "-" 0.012 0.013 . -`

**Comment by daledavies** [comment] 2022-08-15 09:41
I've tried to recreate this using a site with the following URL but it works for me, I've tried a few things to get it to break but everything works fine... `mailto:user@domain.com?subject=Subject`

Could you forward a copy of the site definition in `sites.json`?

**Comment by daledavies** [comment] 2022-08-15 09:42
Also are you using the v1.3.0 docker image?

**Comment by theonekili** [comment] 2022-08-15 12:21
I think you misunderstood my issue:
The link itself works fine, however when I follow the link which should be pointing to the broken image I receive an error 500.
![image](https://user-images.githubusercontent.com/61316292/184632906-a81093bc-54e5-4bc9-ab7c-8967d94f284c.png)

Also I'm running the latest image:

> root@jump:~# docker images
REPOSITORY        TAG       IMAGE ID       CREATED         SIZE
daledavies/jump   latest    65cb5661f33a   2 weeks ago     54.4MB

**Comment by daledavies** [comment] 2022-08-15 20:13
Yes this is what I was trying to recreate, if I use that URL in my own `sites.json` file and set a custom icon the icon loads fine and I do not get a "site could not be found" exception thrown by `icon.php`.

Could you forward the relevant section from your own `sites.json` file?

**Comment by theonekili** [comment] 2022-08-16 07:16
Oh, I'm sorry, I overlooked that paragraph!

Sure, here you are:
![image](https://user-images.githubusercontent.com/61316292/184820201-35f536e0-704f-40e1-8a7b-4710b8a14a22.png)

**Comment by daledavies** [comment] 2022-08-27 06:30
I'm afraid I can't find any way to reproduce the problem. 

Please accept my apologies but I don't know where to go from here, without being able to reproduce the problem myself I am unable to help so I'm closing the issue.

If you are able to debug this yourself and can provide more insight that I can work with then please feel free to reopen it.

**Closed by daledavies** 2022-08-27 06:30 UTC
Labels: triage

**Comment by theonekili** [comment] 2022-09-13 07:02
Hey Dale,

I've got a followup :)
The subject in the mailto links in question had a space, hence the link was considered broken, consider this issue solved :)

**Comment by daledavies** [comment] 2022-09-13 20:36
Awesome, glad you worked it out and thank you for getting back to me :)
